[package]
name = "xc2par"
version = "0.0.1"

[profile.release]
lto = true

[lib]
name = "xc2par"
crate-type = ["rlib", "staticlib"]

[dependencies]
rand = "0.3"
yosys-netlist-json = { path = "../yosys-netlist-json" }
xc2bit = { path = "../xc2bit" }
